# Generated by Django 5.2.7 on 2025-10-13 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daisy',
            old_name='discription',
            new_name='discribtion',
        ),
    ]
