# Generated by Django 5.2.7 on 2025-10-14 14:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0002_rename_discription_daisy_discribtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='daisy',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
