# Generated by Django 5.2.7 on 2025-10-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0003_daisy_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daisy',
            old_name='discribtion',
            new_name='description',
        ),
    ]
