# Generated by Django 5.2.7 on 2025-10-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0004_rename_discribtion_daisy_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='daisy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
